### ISSUE TITLE
Gather members and sort into groups

### ISSUE THREAD

**Issue by ghost** [ScratchLink1/scratchlink1.github.io#1]
Please comment of which group you are willing to work in:
- Frontend (layout and presentation of the website)
- Backend (server side)
If you want to do something different then comment below and I will review it.

**Comment by MossW268** [comment]
For now, I will work at the front end. I will code in the back end if I learn how to do it.

**Comment by ghost** [comment]
okay, please wait until I have a suited landing page framework and then the work can begin...

**Comment by Jemunm** [comment]
I good at CSS and Html, but, I don’t know which side I go on tho.

**Comment by Jemunm** [comment]
Definitely not the server side

**Comment by ghost** [comment]
k. so front-end?

**Comment by Jemunm** [comment]
Yes

**Comment by ghost** [comment]
once I've sketched the mockups you can begin work on the frontend side. for now gather new members (preferably ones with good server experience, we've only got one member doing that... (they haven't accepted the invitation yet)). I will just invite you...

**Comment by Jemunm** [comment]
Okay

**Comment by Accio1** [comment]
I can help do the frontend. What will this website contain?

**Comment by ghost** [comment]
it is a website for organising scratch collabs and shops more easily and efficiently

**Comment by ghost** [comment]
I am closing this issue, if you want to join. Please open a new issue with your strengths and what you can provide to us!
