### ISSUE TITLE
Make landing page

### ISSUE THREAD

**Issue by ghost** [ScratchLink1/scratchlink1.github.io#5]
I have uploaded a rough UI for the landing page in the assets folder (sorry for size) and we can now create that basic ui and then improve it afterwards. We will be using the "numans" font provided by google which I will link to the css. Any futher questions ask below

**Comment by ghost** [comment]
Use the index.html, style.css and script.js No <style> or <script> tags except for linking the js

**Comment by ghost** [comment]
I think forget that design. It isn't very well laid out.

**Comment by Accio1** [comment]
What are the important features that you want on the main page?

**Comment by ghost** [comment]
well, lets say that I have asked someone to work on a UI but no response. Just work on other things for now

**Comment by ghost** [comment]
Could we please not commit to the repo at the moment will the mockup is sorted.

**Comment by Accio1** [comment]
@geographix how is the mockup coming? Do we have a timeline on when it’ll be finished?

**Comment by ghost** [comment]
well, ekmands in but hasn't done too much

**Comment by Accio1** [comment]
Ok, would you like more help creating one?

**Comment by ghost** [comment]
no, because I think ekmand is pretty capable but thanks for the offer! I not sure what to do for now...

**Comment by Accio1** [comment]
Maybe send them a reminder?

**Comment by Accio1** [comment]
In the meantime, are there any other pages which I can start on?

**Comment by ghost** [comment]
hmmm... well, we could probably get scratchverifier to work

**Comment by Accio1** [comment]
> hmmm... well, we could probably get scratchverifier to work

I don't know much about the backend of websites, and that sounds like a backend issue. Do you want me to make the page where users input their username though so that it can get sent to ScratchVerifier, as well as instructions on what to do after they submit their username?

**Comment by ghost** [comment]
I suppose we could make that page to be later changed to fit the ui, yeah. I'll close this issue for now as it is all sorted about the UI, we're just waiting for it to be finished

**Comment by Accio1** [comment]
Is there any more progress on the mockup for the landing page?

**Comment by ghost** [comment]
Yes, Ekmand is working on it and going to probably complete it next week! :thumbsup:
