### ISSUE TITLE
I can help with this

### ISSUE THREAD

**Issue by Accio1** [ScratchLink1/scratchlink1.github.io#7]
I noticed in the other issue about collecting users, you commented that you would like for people who want to help out to create a seperate issue. I think that this project is a really cool idea, so I would like to be able to help out with it.

I am able to code in HTML, CSS, and JavaScript, and I have coded numerous webpages in the past, so I would be able to help with the frontend development of this site. I have also made several projects which interact with the Scratch API, so I would be able to help with that if you require it for this site. I have experience working with groups on GitHub, so I would be able to work well with this one. I'm not really that active on the Requests or Collaboration forums on Scratch, but I do have lots of experience in other forums on Scratch.

**Comment by ghost** [comment]
Okay, great. your in! I think you'll do quite nicely on the frontend of things.

**Comment by Accio1** [comment]
> Okay, great. your in! I think you'll do quite nicely on the frontend of things.

Fantastic! What are we starting with?

**Comment by ghost** [comment]
well, first the UI needs to be made. I have asked @-Ekmand- If he can do it but no reply. Just work on other things for now

**Comment by Accio1** [comment]
> well, first the UI needs to be made. I have asked @-Ekmand- If he can do it but no reply. Just work on other things for now

Like what other things?

**Comment by ghost** [comment]
not this. don't focus on scratchlink1 for now

**Comment by Accio1** [comment]
Okay, once you get a mockup finished of what you want the different pages look like, I can start working on them.

**Comment by ghost** [comment]
yup!

**Comment by Accio1** [comment]
Great! Would you like any help creating mockups?

**Comment by ghost** [comment]
I'm asking @-Ekmand- if he can do it but thanks for the offer!
